name: ClanWar
main: Nozell\ClanWar\Main
version: 1.0.0
api: [5.0.0]
author: Nozell
description: Un plugin de guerra de clanes.
permissions:
  clanwar.default:
    default: true
  clanwar.admin:
    default: op
